###################################################################################
# Thank you Cameron Kerr for https://github.com/cameronkerrnz/logstash-plugin-dev #
###################################################################################
version: 2.1

jobs:
  build:
    parameters:
      logstash-version:
        type: string
    docker:
      - image: cameronkerrnz/logstash-plugin-dev:<< parameters.logstash-version >>
    steps:
      - checkout
      - run:
          name: Ruby Bundle Install
          command: bundle install
      - run:
          name: Ruby Build Gem
          command: gem build logstash-output-mongodb.gemspec

  test:
    parameters:
      logstash-version:
        type: string
    docker:
      - image: cameronkerrnz/logstash-plugin-dev:<< parameters.logstash-version >>
    steps:
      - checkout
      - run:
          name: Ruby Bundle Install
          command: bundle install
      - run:
          name: Ruby Rspec
          command: bundle exec rspec

  publish-github-release:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(cat VERSION)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./logstash-output-mongodb-${VERSION}.gem

workflows:
  version: 2
  main:
    jobs:
      - build:
          name: build-v<< matrix.logstash-version >>
          matrix:
            parameters:
              logstash-version: ["7.9"]
      - test:
          name: test-v<< matrix.logstash-version >>
          matrix:
            parameters:
              logstash-version: ["7.9"]
          requires:
            - build
      - publish-github-release:
          requires:
            - build
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /(?<=^[Vv]|^)(?:(?<major>(?:0|[1-9](?:(?:0|[1-9])+)*))[.](?<minor>(?:0|[1-9](?:(?:0|[1-9])+)*))[.](?<patch>(?:0|[1-9](?:(?:0|[1-9])+)*))(?:-(?<prerelease>(?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:0|[1-9](?:(?:0|[1-9])+)*))(?:[.](?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:0|[1-9](?:(?:0|[1-9])+)*)))*))?(?:[+](?<build>(?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:(?:0|[1-9])+))(?:[.](?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:(?:0|[1-9])+)))*))?)$/
